query USER_LOAD_NUMBERS($userId: BigInt!, $getUsedLoadNumbers: [Boolean!]) {
  loadNumbers(
    condition: { userId: $userId }
    filter: { isUsed: { in: $getUsedLoadNumbers } }
  ) {
    nodes {
      id
      customerId
      customer {
        id
        customerName
        salesUserCode
      }
      orderEntries {
        nodes {
          orderId
          billingCustomer {
            id
            customerName
            salesUserCode
          }
        }
      }
      notes
      orderMaster {
        orderId
        billingCustomer {
          id
          customerName
          salesUserCode
        }
      }
      invoiceHeaders {
        nodes {
          orderId
          billingCustomer {
            id
            customerName
            salesUserCode
          }
        }
      }
      isUsed
    }
  }
}
