query VESSEL_LIST(
  $orderBy: [VesselsOrderBy!]
  $search: [VesselFilter!]
  $countryId: [String!]
  $arrivalPort: [String!]
  $coast: [String!]
  $endDate: Date
  $startDate: Date
) {
  vessels(
    filter: {
      and: $search
      countryId: { in: $countryId }
      arrivalPort: { in: $arrivalPort }
      coast: { in: $coast }
      dischargeDate: {
        greaterThanOrEqualTo: $startDate
        lessThanOrEqualTo: $endDate
      }
    }
    orderBy: $orderBy
  ) {
    nodes {
      arrivalPort
      arrivalDate
      coast
      country {
        countryName
        id
      }
      dischargeDate
      departureDate
      id
      isPre
      invFlag
      searchText
      shipperProjectionVessels {
        nodes {
          id
          shipperId
          shipperProjectionVesselInfosByVesselId {
            nodes {
              arrivalDate
              departureDate
              vesselStatus
              arrivalPort
              id
              vesselName
              vessel {
                id
                vesselId
                shipperProjectionVesselInfosByVesselId {
                  nodes {
                    id
                    vesselName
                  }
                }
              }
              vesselId
              shipperId
              shipper {
                id
                shipperName
                country {
                  id
                  countryName
                }
                shipperProjections {
                  nodes {
                    id
                    submittedAt
                  }
                }
              }
              vessel {
                id
                shipper {
                  shipperName
                  id
                }
              }
              projection {
                id
                submittedAt
                approvedAt
                rejectedAt
                jvComments
                shipperComments
                reviewStatus
                shipper {
                  id
                  shipperName
                }
              }
              shipperProjectionEntriesByVesselInfoId {
                nodes {
                  id
                  palletCount
                  productId
                  vesselInfoId
                }
              }
            }
          }
        }
      }
      vesselName
      vesselCode
      warehouse {
        id
        warehouseName
      }
    }
    totalCount
  }
}
