query VESSEL_LIST(
  $orderBy: [VesselsOrderBy!]
  $search: [VesselFilter!]
  $countryId: [String!]
  $arrivalPort: [String!]
  $coast: [String!]
  $endDate: Date
  $startDate: Date
) {
  vessels(
    filter: {
      and: $search
      countryId: { in: $countryId }
      arrivalPort: { in: $arrivalPort }
      coast: { in: $coast }
      dischargeDate: {
        greaterThanOrEqualTo: $startDate
        lessThanOrEqualTo: $endDate
      }
    }
    orderBy: $orderBy
  ) {
    nodes {
      coast
      country {
        countryName
        id
      }
      dischargeDate
      departureDate
      id
      vesselName
      vesselCode
      warehouse {
        id
        warehouseName
      }
    }
    totalCount
  }
}
