query COMMON_SPECIES_LIST(
  $speciesOrderBy: [CommonSpeciesOrderBy!]
  $varietiesOrderBy: [CommonVarietiesOrderBy!]
  $sizesOrderBy: [CommonSizesOrderBy!]
  $packTypesOrderBy: [CommonPackTypesOrderBy!]
  $search: [CommonSpeciesFilter!]
) {
  commonSpecieses(filter: { and: $search }, orderBy: $speciesOrderBy) {
    nodes {
      id
      defaultInvSortKey
      palletWeight
      speciesDescription
      speciesName
      uiColor
      productSpeciesId
      productSpeciesByCommonSpeciesProductSpeciesCommonSpeciesIdAndProductSpeciesId {
        nodes {
          id
          speciesDescription
        }
      }
      commonSpeciesTags {
        nodes {
          commonSpeciesId
          nodeId
          tagText
        }
      }
      commonCategory {
        categoryDescription
        categoryName
        id
        uiColor
      }
      commonVarieties(orderBy: $varietiesOrderBy) {
        nodes {
          id
          uiColor
          varietyName
          varietyDescription
          productVarietyId
          productVarietiesByCommonVarietyProductVarietyCommonVarietyIdAndProductVarietyId {
            nodes {
              id
              varietyDescription
            }
          }
          commonVarietyTags {
            nodes {
              tagText
              nodeId
              commonVarietyId
            }
          }
        }
      }
      commonSizes(orderBy: $sizesOrderBy) {
        nodes {
          id
          productSizeId
          productSizesByCommonSizeProductSizeCommonSizeIdAndProductSizeId {
            nodes {
              id
              jvDescription
            }
          }
          sizeDescription
          sizeName
          commonSizeTags {
            nodes {
              commonSizeId
              nodeId
              tagText
            }
          }
        }
      }
      commonPackTypes(orderBy: $packTypesOrderBy) {
        nodes {
          id
          isRepack
          palletWeight
          packMasterId
          packMaster {
            id
            packDescription
          }
          packMastersByCommonPackTypePackMasterCommonPackTypeIdAndPackMasterId {
            nodes {
              id
              packDescription
            }
          }
          packTypeDescription
          packTypeName
          commonPackTypeTags {
            nodes {
              commonPackTypeId
              nodeId
              tagText
            }
          }
        }
      }
    }
  }
}
