query PRODUCT_MASTER_LIST(
  $orderBy: [ProductMastersOrderBy!]
  $search: [ProductMasterFilter!]
  $last: Int!
) {
  productMasters(filter: { and: $search }, orderBy: $orderBy, last: $last) {
    nodes {
      defaultPalletQuantity
      id
      lotNumber
      packType {
        jvPackCode
        packDescription
      }
      sizes {
        nodes {
          jvCode
          combineDescription
          jvDescription
        }
      }
      species {
        speciesDescription
      }
      variety {
        varietyDescription
      }
    }
    totalCount
  }
}
