query INTERNAL_CONTACT_DETAILS($id: BigInt!) {
  personContact(id: $id) {
    cellPhone
    email
    firstName
    homePhone
    id
    imageSrc
    isPrimary
    lastName
    roles
    secondaryEmail
    workExtension
    workPhone
    customersByCustomerPersonContactPersonContactIdAndCustomerId {
      nodes {
        customerName
        id
      }
    }
    shippersByShipperPersonContactPersonContactIdAndShipperId {
      nodes {
        shipperName
        id
      }
    }
    warehousesByWarehousePersonContactPersonContactIdAndWarehouseId {
      nodes {
        warehouseName
        id
      }
    }
    vendorsByVendorPersonContactPersonContactIdAndVendorId {
      nodes {
        vendorName
        id
      }
    }
  }
}
