query INTERNAL_CONTACT_LIST(
  $search: [PersonContactFilter!]
  $orderBy: [PersonContactsOrderBy!]
) {
  personContacts(
    condition: { isInternal: true }
    filter: { and: $search }
    orderBy: $orderBy
  ) {
    nodes {
      id
      firstName
      lastName
      email
      isPrimary
      homeExtension
      workExtension
    }
    totalCount
  }
}
