query PERSON_CONTACT_LIST($search: String, $orderBy: [PersonContactsOrderBy!]) {
  personContacts(
    filter: { searchText: { includesInsensitive: $search } }
    orderBy: $orderBy
  ) {
    nodes {
      email
      firstName
      id
      lastName
      customerId
      customer {
        customerName
      }
      shipperId
      shipper {
        shipperName
      }
      warehouseId
      warehouse {
        warehouseName
      }
    }
    totalCount
  }
}
