query VESSEL_CONTROL_LIST($dateFilter: VesselControlFilter!) {
  vesselControls(filter: $dateFilter) {
    nodes {
      approval1
      approval2
      dateSent
      id
      isLiquidated
      nodeId
      notes1
      notes2
      shipper {
        id
        shipperName
        vesselControlDaysUntilDue
      }
      pallets {
        totalCount
      }
      palletsShipped
      unpaids {
        nodes {
          id
          invoiceId
          invoice {
            id
            actualShipDate
            amountOwed
            billingCustomer {
              id
              customerName
              volumeDiscounts {
                nodes {
                  volumeDiscountCode
                  amount
                }
              }
            }
            truckLoadId
            salesUserCode
            salesUser {
              userCode
              personContact {
                firstName
                email
              }
              id
            }
            invoiceId
            orderId
            paidCode
            flag
            totalAmount
            totalAmountsByVesselAndShipper {
              nodes
            }
            conditionCode
            creditCode
            netAmountDue
          }
          shipperId
          vesselCode
          isApproved
          isUrgent
          notes
        }
      }
      vessel {
        id
        arrivalDate
        dischargeDate
        vesselName
        vesselCode
        country {
          id
          countryName
        }
        warehouse {
          id
          warehouseName
        }
      }
    }
  }
}
