query VESSEL_CONTROL_LIST($dateFilter: VesselControlFilter!) {
  allVesselControls(filter: $dateFilter) {
    nodes {
      approval1
      approval2
      dateSent
      id
      isLiquidated
      nodeId
      notes1
      notes2
      shipper {
        id
        shipperName
        vesselControlDaysUntilDue
      }
      unpaids {
        nodes {
          id
          invoiceId
          invoice {
            paidCode
          }
          shipperId
          vesselCode
          isApproved
          isUrgent
          notes
        }
      }
      pallets {
        nodes {
          id
          invoiceHeaders {
            nodes {
              id
              actualShipDate
              amountOwed
              billingCustomer {
                id
                customerName
              }
              truckLoadId
              salesUserCode
              salesUser {
                userCode
                personContact {
                  firstName
                  email
                }
                id
              }
              invoiceId
              orderId
              paidCode
              flag
              totalAmount
              totalCreditAmount
              conditionCode
              creditCode
            }
          }
          billOfLading
          palletId
          shipped
          searchText
        }
      }
      vessel {
        id
        arrivalDate
        dischargeDate
        vesselName
        vesselCode
        country {
          id
          countryName
        }
        warehouse {
          id
          warehouseName
        }
      }
    }
  }
}
