query VESSEL_LIST(
  $orderBy: [VesselsOrderBy!]
  $endDate: Date
  $startDate: Date
) {
  vessels(
    condition: { isAvailable: false }
    filter: {
      dischargeDate: {
        greaterThanOrEqualTo: $startDate
        lessThanOrEqualTo: $endDate
      }
    }
    orderBy: $orderBy
  ) {
    nodes {
      id
      arrivalDate
      coast
      dischargeDate
      isPre
      vesselCode
      vesselName
      warehouse {
        id
        warehouseName
      }
      scheduleNotes
    }
    totalCount
  }
}
