query SHIPPER_LIST(
  $country: [String!]
  $orderBy: [ShippersOrderBy!]
  $search: String
) {
  shippers(
    filter: {
      country: { id: { in: $country } }
      searchText: { includesInsensitive: $search }
    }
    orderBy: $orderBy
  ) {
    nodes {
      id
      country {
        countryName
      }
      groupId
      personContactsByShipperPersonContactShipperIdAndPersonContactId {
        nodes {
          shippersByShipperPersonContactPersonContactIdAndShipperId {
            nodes {
              shipperName
            }
          }
          email
          firstName
          id
          isPrimary
          lastName
          workPhone
        }
      }
      shipperName
    }
    totalCount
  }
}
