query COMMON_SIZE($id: BigInt!) {
  commonSize(id: $id) {
    commonSpecies {
      id
      speciesName
      commonCategory {
        id
        categoryName
      }
      commonSizes {
        nodes {
          id
          sizeName
          commonSizeTags {
            nodes {
              tagText
              nodeId
              commonSizeId
            }
          }
        }
      }
    }
    id
    defaultInvSortKey
    productSizeId
    productSizesByCommonSizeProductSizeCommonSizeIdAndProductSizeId {
      nodes {
        id
        combineDescription
        jvDescription
      }
    }
    sizeDescription
    sizeName
    commonSizeTags {
      nodes {
        commonSizeId
        nodeId
        tagText
      }
    }
  }
}
