query COMMON_CATEGORIES_LIST(
  $speciesOrderBy: [CommonSpeciesOrderBy!]
  $search: [CommonSpeciesFilter!]
) {
  commonCategories {
    nodes {
      id
      categoryDescription
      categoryName
      uiColor
      commonSpecieses(filter: { and: $search }, orderBy: $speciesOrderBy) {
        nodes {
          id
          speciesName
          speciesDescription
          uiColor
        }
      }
    }
  }
}
