version: '3'

services:
  db-2:
    container_name: jv-db-2
    platform: linux/amd64
    build: ./db
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./volumes/db-2:/var/lib/postgresql/data
  db:
    container_name: jv-db
    image: postgres:13
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ${BACKUP_DIRECTORY}:/backups
  db-admin:
    container_name: jv-dbadmin
    image: taivokasper/omnidb
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - 8080:8080
    volumes:
      - dbadmin-data:/etc/omnidb
  db-backup:
    container_name: jv-backup
    image: prodrigestivill/postgres-backup-local
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env
    ports:
      - 8081:8080
    volumes:
      - ${BACKUP_DIRECTORY}:/backups
  graphql:
    container_name: jv-graphql
    build: ./graphql
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - 5433:5433
    restart: always
    volumes:
      - ${PERU_INSPECTIONS_DIRECTORY}:/peru-departure-inspections
      - ${CHILE_INSPECTIONS_DIRECTORY}:/chile-departure-inspections
      - ${PSA_INSPECTIONS_DIRECTORY}:/psa-arrival-inspections
  server:
    container_name: jv-server
    build: ./server
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - 3001:3001
    volumes:
      - ./server:/server
      - server_nodemodules:/server/node_modules
      - ${PERU_INSPECTIONS_DIRECTORY}:/server/static/peru-departure-inspections
      - ${CHILE_INSPECTIONS_DIRECTORY}:/server/static/chile-departure-inspections
      - ${PSA_INSPECTIONS_DIRECTORY}:/server/static/psa-arrival-inspections
  worker:
    container_name: jv-worker
    build: ./worker
    depends_on:
      - db
      - graphql
    env_file:
      - ./.env
    ports:
      - 3002:3002
    volumes:
      - ./worker:/worker
      - worker_nodemodules:/worker/node_modules
      - ${CHILE_INSPECTIONS_DIRECTORY}:/chile-departure-inspections
      - ${PERU_INSPECTIONS_DIRECTORY}:/peru-departure-inspections
      - ${PSA_INSPECTIONS_DIRECTORY}:/psa-arrival-inspections
      - ${JV_QC_INSPECTIONS_DIRECTORY}:/jv-qc-inspections
  client:
    container_name: jv-client
    build: ./client
    depends_on:
      - db
      - graphql
      - server
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
      - client_nodemodules:/client/node_modules

volumes:
  db-data:
  db-data-2:
  dbadmin-data:
  worker_nodemodules:
  client_nodemodules:
  server_nodemodules:
