CREATE TABLE peru_departure_inspection_pallet (
	id BIGSERIAL PRIMARY KEY,
	pallet_id TEXT NOT NULL,
	container_id TEXT NOT NULL,
	size TEXT NOT NULL,
	net_weight NUMERIC NOT NULL,
	opening_score NUMERIC NOT NULL,
	color_score NUMERIC NOT NULL,
	stem_score NUMERIC NOT NULL,
	texture_score NUMERIC NOT NULL,
	bunches_per_box NUMERIC NOT NULL,
	brix NUMERIC NOT NULL,
	quality_score NUMERIC NOT NULL,
	condition_score NUMERIC NOT NULL,
	straggly_tight_pct NUMERIC NOT NULL,
	surface_disc_pct NUMERIC NOT NULL,
	russet_scars_pct NUMERIC NOT NULL,
	sunburn_pct NUMERIC NOT NULL,
	undersized_bunches_pct NUMERIC NOT NULL,
	other_defects_pct NUMERIC NOT NULL,
	total_quality_defects_pct NUMERIC NOT NULL,
	stem_dehy_pct NUMERIC NOT NULL,
	glassy_weak_pct NUMERIC NOT NULL,
	decay_pct NUMERIC NOT NULL,
	split_crushed_pct NUMERIC NOT NULL,
	dry_split_pct NUMERIC NOT NULL,
	wet_sticky_pct NUMERIC NOT NULL,
	waterberries_pct NUMERIC NOT NULL,
	shatter_pct NUMERIC NOT NULL,
	total_condition_defects_pct NUMERIC NOT NULL,
	total_defects_pct NUMERIC NOT NULL,
	CONSTRAINT fk_container
		FOREIGN KEY(container_id)
		REFERENCES peru_departure_inspection(container_id)
		ON DELETE CASCADE
);

INSERT INTO peru_departure_inspection_pallet (
	pallet_id,
	container_id,
	size,
	net_weight,
	opening_score,
	color_score,
	stem_score,
	texture_score,
	bunches_per_box,
	brix,
	quality_score,
	condition_score,
	straggly_tight_pct,
	surface_disc_pct,
	russet_scars_pct,
	sunburn_pct,
	undersized_bunches_pct,
	other_defects_pct,
	total_quality_defects_pct,
	stem_dehy_pct,
	glassy_weak_pct,
	decay_pct,
	split_crushed_pct,
	dry_split_pct,
	wet_sticky_pct,
	waterberries_pct,
	shatter_pct,
	total_condition_defects_pct,
	total_defects_pct
) VALUES (
	'average',
	'BMOU9310631',
	'',
	8.23,
	1,
	2,
	1,
	1,
	14,
	14.9,
	1,
	3,
	0.8,
	0.0,
	0.4,
	0.0,
	1.1,
	0.0,
	2.4,
	0.0,
	3.5,
	0.0,
	0.0,
	0.0,
	0.0,
	0.1,
	1.9,
	10.7,
	11.3
);
