CREATE TABLE peru_departure_inspection (
	container_id TEXT NOT NULL PRIMARY KEY,
	avg_bunches_per_box NUMERIC NOT NULL,
	avg_net_weight NUMERIC NOT NULL,
	bags_per_box NUMERIC NOT NULL,
	bag_type TEXT,
	brand TEXT NOT NULL,
	brix_avg NUMERIC NOT NULL,
	brix_max NUMERIC NOT NULL,
	brix_min NUMERIC NOT NULL,
	category TEXT NOT NULL,
	comments TEXT NOT NULL,
	condition_score NUMERIC NOT NULL,
	departure_week TEXT NOT NULL,
	destination TEXT NOT NULL,
	exporter TEXT NOT NULL,
	inspection_date date NOT NULL,
	packing_date date NOT NULL,
	packing_house TEXT NOT NULL,
	packing_material TEXT NOT NULL,
	presentation TEXT NOT NULL,
	quality_score NUMERIC NOT NULL,
	variety TEXT NOT NULL
)
