query WAREHOUSE_DETAILS($id: String!, $orderBy: [PersonContactsOrderBy!]) {
  warehouse(id: $id) {
    address1
    address2
    address3
    city
    cityTaxCode
    country {
      countryName
    }
    countyTaxCode
    id
    miscTaxCode
    outQueue
    personContactsByWarehousePersonContactWarehouseIdAndPersonContactId(
      orderBy: $orderBy
    ) {
      nodes {
        warehousesByWarehousePersonContactPersonContactIdAndWarehouseId {
          nodes {
            warehouseName
            id
          }
        }
        email
        firstName
        id
        isPrimary
        lastName
        workPhone
      }
    }
    phone
    postalState
    stateTaxCode
    warehouseName
    zipCode
  }
}
