query WAREHOUSE_LIST(
  $city: [String!]
  $postalState: [String!]
  $orderBy: [WarehousesOrderBy!]
  $search: [WarehouseFilter!]
) {
  warehouses(
    filter: {
      and: $search
      city: { in: $city }
      postalState: { in: $postalState }
    }
    orderBy: $orderBy
  ) {
    nodes {
      id
      city
      personContactsByWarehousePersonContactWarehouseIdAndPersonContactId {
        nodes {
          warehousesByWarehousePersonContactPersonContactIdAndWarehouseId {
            nodes {
              warehouseName
              id
            }
          }
          email
          firstName
          id
          isPrimary
          lastName
          workPhone
        }
      }
      phone
      postalState
      zipCode
      warehouseName
    }
    totalCount
  }
}
