query INVENTORY_ITEM_DETAILS($id: BigInt!) {
  inventoryItem(id: $id) {
    coast
    country {
      countryName
      id
    }
    id
    jvLotNumber
    pallets {
      nodes {
        containerId
        currentBoxQuantity
        growerId
        id
        orderId
        palletId
        packDate
        shipped
      }
      totalCount
    }
    palletsAvailable
    palletsCommitted
    palletsOnHand
    palletsReceived
    palletsShipped
    palletsTransferredIn
    palletsTransferredOut
    plu
    product {
      id
      species {
        id
        speciesDescription
        commonSpecies {
          id
          speciesName
        }
      }
      variety {
        id
        varietyDescription
        commonVariety {
          id
          varietyName
        }
      }
      sizes {
        nodes {
          id
          jvDescription
          commonSize {
            id
            sizeName
          }
        }
      }
      packType {
        id
        packDescription
        label {
          id
          labelName
        }
        customerSpecial {
          id
          customerName
        }
        commonPackType {
          id
          isRepack
          packTypeName
        }
      }
    }
    shipper {
      id
      shipperName
    }
    specialLotNumber
    storageRank
    vessel {
      id
      dischargeDate
      isPre
      vesselCode
      vesselName
    }
    warehouse {
      id
      warehouseName
    }
  }
}
