query INVENTORY_ITEM_LIST($startDate: Date!, $endDate: Date!) {
  inventoryItems(
    filter: {
      and: {
        vesselDischargeDate: {
          greaterThanOrEqualTo: $startDate
          lessThanOrEqualTo: $endDate
        }
        vesselInvFlag: { equalTo: true }
        not: {
          and: {
            palletsOnHand: { equalTo: "0" }
            palletsCommitted: { equalTo: "0" }
          }
        }
      }
    }
  ) {
    nodes {
      coast
      country {
        id
        countryName
      }
      id
      jvLotNumber
      palletsAvailable
      palletsCommitted
      palletsReceived
      palletsShipped
      palletsOnHand
      plu
      product {
        id
        species {
          id
          speciesDescription
        }
        variety {
          id
          varietyDescription
        }
        sizes(first: 1) {
          nodes {
            id
            combineDescription
          }
        }
        packType {
          commonPackType {
            id
            boxCount
          }
          defaultPalletQuantity
          packDescription
          id
          label {
            id
            labelCode
            labelName
          }
          customerSpecial {
            id
            customerName
          }
        }
      }
      shipper {
        shipperName
        id
      }
      vessel {
        id
        coast
        dischargeDate
        vesselCode
        vesselName
        isPre
      }
      warehouse {
        id
        warehouseName
      }
    }
  }
}
