query EXPENSE_HEADER_DETAILS($invoiceId: String!) {
  expenseHeaders(condition: { invoiceId: $invoiceId }) {
    nodes {
      id
      vendorId
      voucherId
      sequenceId
      quantity
      unitPrice
      itemAmount
      billOfLadingId
      productCode
      palletId
      shipperId
      notes
    }
  }
}
