query EXPENSE_HEADER_LIST(
  $expenseCode: [String!]
  $vesselCode: [String!]
  $orderBy: [ExpenseHeadersOrderBy!]
  $search: [ExpenseHeaderFilter!]
  $endDate: Date
  $startDate: Date
) {
  expenseHeaders(
    filter: {
      and: $search
      expenseCode: { in: $expenseCode }
      vesselCode: { in: $vesselCode }
      or: {
        vesselDischargeDate: {
          greaterThanOrEqualTo: $startDate
          lessThanOrEqualTo: $endDate
        }
      }
    }
    orderBy: $orderBy
  ) {
    nodes {
      id
      vendor {
        id
        vendorName
      }
      voucherId
      invoiceId
      isEstimated
      paidCode
      expenseAmount
      checkNumber
      expenseCode
      truckLoadId
      vesselDischargeDate
      vessel {
        id
        dischargeDate
        vesselCode
        vesselName
      }
    }
    totalCount
  }
}
