query EXPENSE_HEADER_REVIEW_LIST($vesselCode: String!, $shipperId: String!) {
  expenseHeaderReviewsList(
    vesselCodeParam: $vesselCode
    shipperIdParam: $shipperId
  ) {
    nodes {
      id
      vendorId
      voucherId
      expenseCode
      isApproved
      notes
    }
  }
}