query EXPENSE_HEADER_LIST($vesselCode: String!, $shipperId: String!) {
  expenseHeaderSummaryView(
    vesselCodeParam: $vesselCode
  ) {
    nodes {
      vendorId
      vendor {
        id
        vendorName
      }
      voucherId
      invoiceId
      isEstimated
      isProrate
      paidCode
      expenseAmount
      checkNumber
      expenseCode
      truckLoadId
      receivableCut
      apHide
      entryDate
      customsEntryCode
      vesselDischargeDate
      vesselCode
      vessel {
        dischargeDate
        vesselCode
        vesselName
      }
      items(filter: { shipperId: { equalTo: $shipperId }, vesselCode: { equalTo: $vesselCode } }) {
        nodes {
          vendorId
          voucherId
          sequenceId
          quantity
          unitPrice
          itemAmount
          billOfLadingId
          productCode
          pallet {
            id
            palletId
            vesselCode
          }
          shipper {
            id
            shipperName
          }
          expenseCode
          vesselCode
        }
      }
    }
    totalCount
  }
}
