query VESSEL_LIST($search: [VesselFilter!]) {
  vessels(
    condition: { invFlag: true }
    filter: { and: $search }
    orderBy: VESSEL_CODE_ASC
  ) {
    nodes {
      dischargeDate
      id
      inventoryItems {
        nodes {
          id
          shipper {
            shipperName
            id
          }
        }
      }
      vesselName
      vesselCode
    }
    totalCount
  }
}
