query TRUCK_LOAD_DETAILS($truckLoadId: String!) {
  truckLoads(condition: { loadId: $truckLoadId }) {
    nodes {
      id
      loadId
      loadStatus
      vendor {
        id
        vendorName
      }
      fob
      shipDate
      ryanNumber
      truckerName
      expeditorName
      timeStarted
      timeCompleted
      timeIn
      timeOut
      timeConfirmed
      warehouse {
        id
        warehouseName
      }
      changeFlag
      licensePlate
      inUse
      cartage
      cartageVendorId
      temperature
      loadLock
      notes
      rejectedTruckLoads {
        nodes {
          loadId
          invoiceHeaders {
            nodes {
              orderId
            }
          }
        }
      }
      splitTruckLoads {
        nodes {
          loadId
          invoiceHeaders {
            nodes {
              orderId
            }
          }
        }
      }
      originalTruckLoad {
        loadId
        invoiceHeaders {
          nodes {
            orderId
          }
        }
      }
      invoiceHeaders {
        nodes {
          orderId
        }
      }
      orderMaster {
        backOrderId
        billingCustomer {
          id
          customerName
        }
        expectedShipDate
        id
        items {
          nodes {
            backOrderId
            boxCount
            deliveryCharge
            id
            inventoryItem {
              id
              vessel {
                id
                vesselCode
                vesselName
                isPre
              }
              coast
              plu
              product {
                id
                species {
                  id
                  speciesDescription
                  commonSpecies {
                    id
                    palletWeight
                  }
                }
                variety {
                  id
                  varietyDescription
                }
              }
              sizes {
                nodes {
                  id
                  combineDescription
                  jvDescription
                }
              }
              packType {
                id
                packDescription
                commonPackType {
                  id
                  palletWeight
                }
              }
            }
            isBundle
            itemStatus
            lineId
            orderId
            palletCount
            notes
            unitSellPrice
            locationId
            shipperId
          }
        }
        orderId
        orderStatus
        shipWarehouse {
          id
          warehouseName
        }
        truckLoadId
      }
      pallets {
        nodes {
          containerId
          currentBoxQuantity
          growerId
          id
          locationId
          orderId
          palletId
          packDate
          shipped
          product {
            id
            species {
              id
              speciesDescription
              commonSpecies {
                id
                palletWeight
              }
            }
          }
          packType {
            id
            packDescription
            commonPackType {
              id
              palletWeight
            }
          }
        }
      }
    }
  }
}
