query TRUCK_LOAD_LIST(
  $orderBy: [TruckLoadsOrderBy!]
  $search: [TruckLoadFilter!]
  $endDate: Date
  $startDate: Date
) {
  truckLoads(
    filter: {
      and: $search
      or: {
        shipDate: {
          greaterThanOrEqualTo: $startDate
          lessThanOrEqualTo: $endDate
        }
      }
    }
    orderBy: $orderBy
  ) {
    nodes {
      id
      loadId
      loadStatus
      vendorId
      fob
      shipDate
      count
      warehouse {
        id
        warehouseName
      }
    }
    totalCount
  }
}
