query TRUCK_LOAD_LIST(
  $orderBy: [TruckLoadsOrderBy!]
  $search: [TruckLoadFilter!]
  $endDate: Date
  $startDate: Date
  $vendorId: [String!]
) {
  truckLoads(
    filter: {
      and: $search
      vendorId: { in: $vendorId }
      or: {
        shipDate: {
          greaterThanOrEqualTo: $startDate
          lessThanOrEqualTo: $endDate
        }
      }
    }
    orderBy: $orderBy
  ) {
    nodes {
      id
      loadId
      loadStatus
      vendor {
        id
        vendorName
      }
      fob
      shipDate
      count
      orderMaster {
        id
        billingCustomer {
          id
          customerName
        }
        expectedShipDate
        items {
          nodes {
            id
            inventoryItem {
              id
              product {
                id
                species {
                  id
                  speciesDescription
                  commonSpecies {
                    id
                    palletWeight
                  }
                }
              }
              packType {
                id
                packDescription
                commonPackType {
                  id
                  palletWeight
                }
              }
            }
          }
        }
      }
      invoiceHeaders {
        nodes {
          id
          billingCustomer {
            id
            customerName
          }
          expectedShipDate
        }
      }
    }
    totalCount
  }
}
