query DISTINCT_VALUES(
  $columnName: String
  $tableName: String
  $schemaName: String
) {
  distinctValues(
    columnName: $columnName
    tableName: $tableName
    schemaName: $schemaName
  ) {
    nodes
  }
}
