query OFFICE_DETAILS($id: String!) {
  office(id: $id) {
    address1
    address2
    city
    company {
      companyName
    }
    email
    id
    officeDescription
    officeName
    phone
    postalState
    secondaryEmail
    secondaryPhone
    zipCode
  }
}
