query COMMON_PACK_TYPE($id: BigInt!) {
  commonPackType(id: $id) {
    commonSpecies {
      id
      speciesName
      commonCategory {
        id
        categoryName
      }
      commonPackTypes {
        nodes {
          id
          isRepack
          packTypeName
          commonPackTypeTags {
            nodes {
              tagText
              nodeId
              commonPackTypeId
            }
          }
        }
      }
    }
    id
    defaultInvSortKey
    isRepack
    packMasterId
    packMastersByCommonPackTypePackMasterCommonPackTypeIdAndPackMasterId {
      nodes {
        id
        packDescription
      }
    }
    packTypeDescription
    packTypeName
    commonPackTypeTags {
      nodes {
        commonPackTypeId
        nodeId
        tagText
      }
    }
  }
}
