query COMMON_PACK_TYPE($id: BigInt!) {
  commonPackType(id: $id) {
    commonSpecies {
      id
      speciesName
      commonCategory {
        id
        categoryName
      }
      commonPackTypes {
        nodes {
          id
          repackStyle {
            id
            styleName
          }
          packTypeName
          commonPackTypeTags {
            nodes {
              tagText
              nodeId
              commonPackTypeId
            }
          }
        }
      }
    }
    boxCount
    id
    defaultInvSortKey
    repackStyleId
    repackStyle {
      id
      styleName
      styleDescription
      lqdCode
      filmLength
      packOutWeight
    }
    palletWeight
    packMasterId
    packMastersByCommonPackTypePackMasterCommonPackTypeIdAndPackMasterId {
      nodes {
        id
        packDescription
      }
    }
    packTypeDescription
    packTypeName
    commonPackTypeTags {
      nodes {
        commonPackTypeId
        nodeId
        tagText
      }
    }
  }
}
