query USER_DETAILS(
  $id: BigInt!
  $isRead: [Boolean!]
  $getUsedLoadNumbers: [Boolean!]
) {
  user(id: $id) {
    id
    loadNumbers(filter: { isUsed: { in: $getUsedLoadNumbers } }) {
      nodes {
        id
        customerId
        customer {
          id
          customerName
          salesUserCode
        }
        orderEntries {
          nodes {
            orderId
            billingCustomer {
              id
              customerName
              salesUserCode
            }
          }
        }
        notes
        orderMaster {
          orderId
          billingCustomer {
            id
            customerName
            salesUserCode
          }
        }
        invoiceHeader {
          orderId
          billingCustomer {
            id
            customerName
            salesUserCode
          }
        }
        isUsed
      }
    }
    defaultCoast
    pin
    personContact {
      firstName
      id
      email
    }
    userCode
    userBookmarks {
      nodes {
        id
        category
        linkUrl
        linkDescription
        sortOrder
      }
    }
    userMessages(filter: { isRead: { in: $isRead } }) {
      nodes {
        actionLink
        actionText
        details
        header
        id
        isRead
        messageDate
        priority
      }
    }
    userRoles {
      nodes {
        roleName
        userId
      }
    }
  }
}
