query USER_DETAILS($id: BigInt!, $isRead: [Boolean!]) {
  user(id: $id) {
    id
    loadNumbers(filter: { hasOrderEntries: { equalTo: false } }) {
      nodes {
        id
        customerId
        customer {
          id
          customerName
          salesUserCode
        }
      }
    }
    pin
    personContact {
      firstName
      id
      email
    }
    userCode
    userMessages(filter: { isRead: { in: $isRead } }) {
      nodes {
        actionLink
        actionText
        details
        header
        id
        isRead
        messageDate
        priority
      }
    }
    userRoles {
      nodes {
        roleName
        userId
      }
    }
  }
}
