query REPACK_QUEUE(
  $orderBy: [RepackQueuesOrderBy!]
  $repackDate: DateFilter!
  $search: [RepackQueueFilter!]
) {
  repackQueues(
    filter: { and: $search, repackDate: $repackDate }
    orderBy: $orderBy
  ) {
    nodes {
      id
      orderId
      repackCode
      repackDate
      repackStyleId
      warehouseId
      palletCount
      shipDate
      delDate
      warehouse {
        id
        warehouseName
      }
      repackStyle {
        id
        styleName
        styleDescription
        lqdCode
      }
      invoices {
        totalCount
      }
      orderNotes
      notes
    }
    totalCount
  }
}
