query PERU_DEPARTURE_INSPECTIONS_LIST(
  $endDate: Date
  $orderBy: [PeruDepartureInspectionsOrderBy!]
  $search: String
  $startDate: Date
  $exporter: [String!]
  $variety: [String!]
) {
  peruDepartureInspections(
    filter: {
      searchText: { includesInsensitive: $search }
      exporter: { in: $exporter }
      variety: { in: $variety }
      or: {
        inspectionDate: {
          greaterThanOrEqualTo: $startDate
          lessThanOrEqualTo: $endDate
        }
        packingDate: {
          greaterThanOrEqualTo: $startDate
          lessThanOrEqualTo: $endDate
        }
      }
    }
    orderBy: $orderBy
  ) {
    nodes {
      containerId
      conditionScore
      exporter
      imageUrls
      inspectionDate
      packingDate
      qualityScore
      variety
    }
    totalCount
  }
}
