mutation BULK_UPSERT_CUSTOMER_PROGRAM(
  $customerPrograms: [CustomerProgramInput]!
) {
  bulkUpsertCustomerProgram(input: { programs: $customerPrograms }) {
    customerPrograms {
      id
      commonSpeciesId
      commonVarietyId
      commonSizeId
      commonPackTypeId
      plu
    }
  }
}
