query CUSTOMER_PROGRAM_LIST(
  $arrivalPort: String!
  $endDate: Date!
  $startDate: Date!
  $customerId: String
) {
  customerPrograms(
    condition: { arrivalPort: $arrivalPort, customerId: $customerId }
    filter: {
      customerProgramEntries: {
        some: {
          programDate: {
            greaterThanOrEqualTo: $startDate
            lessThanOrEqualTo: $endDate
          }
        }
      }
    }
  ) {
    nodes {
      arrivalPort
      commonPackType {
        id
        packTypeName
      }
      commonPackTypeId
      commonSize {
        id
        sizeName
      }
      commonSizeId
      commonSpecies {
        id
        speciesName
        uiColor
      }
      commonSpeciesId
      commonVariety {
        id
        uiColor
        varietyName
      }
      commonVarietyId
      id
      notes
      plu
      customerId
      customer {
        id
        customerName
      }
      customerProgramEntries {
        nodes {
          id
          isAdWeek
          notes
          palletCount
          programDate
          searchText
          customerProgram {
            id
            plu
            notes
            arrivalPort
            commonSpecies {
              id
              speciesName
            }
            commonVariety {
              id
              varietyName
            }
            commonSize {
              id
              sizeName
            }
            commonPackType {
              id
              packTypeName
            }
            customer {
              id
              customerName
            }
          }
          shipperProgramEntryCustomerProgramEntries {
            nodes {
              customerProgramEntryId
              id
              palletCount
              shipperProgramEntryId
              shipperProgramEntry {
                id
                shipperProgram {
                  id
                  shipper {
                    id
                    shipperName
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
