query INVENTORY_ITEM_LIST {
  inventoryItems(filter: { palletsOnHand: { notEqualTo: "0" } }) {
    nodes {
      coast
      country {
        id
        countryName
      }
      id
      palletsAvailable
      palletsCommitted
      palletsReceived
      palletsShipped
      palletsOnHand
      plu
      product {
        id
        species {
          id
          speciesDescription
          commonSpecieses {
            nodes {
              id
              defaultInvSortKey
              productSpeciesId
              commonSpeciesTags {
                nodes {
                  nodeId
                  tagText
                }
              }
            }
          }
        }
        variety {
          id
          varietyDescription
          commonVarieties {
            nodes {
              id
              defaultInvSortKey
              productVarietyId
              commonVarietyTags {
                nodes {
                  nodeId
                  tagText
                }
              }
            }
          }
        }
        sizes(first: 1) {
          nodes {
            id
            jvDescription
            commonSizes {
              nodes {
                id
                defaultInvSortKey
                productSizeId
                commonSizeTags {
                  nodes {
                    nodeId
                    tagText
                  }
                }
              }
            }
          }
        }
        packType {
          packDescription
          id
          label {
            labelName
          }
          commonPackTypes {
            nodes {
              id
              defaultInvSortKey
              packMasterId
              commonPackTypeTags {
                nodes {
                  nodeId
                  tagText
                }
              }
            }
          }
        }
      }
      shipper {
        shipperName
        id
      }
      vessel {
        id
        dischargeDate
        vesselCode
        vesselName
        isPre
      }
      warehouse {
        id
        warehouseName
      }
    }
  }
}
