query UNPAID_LIST($orderBy: [UnpaidsOrderBy!]) {
  unpaids(orderBy: $orderBy) {
    nodes {
      id
      invoice {
        id
        actualShipDate
        amountOwed
        salesUser {
          userCode
          id
        }
        invoiceId
        orderId
        paidCode
        billingCustomer {
          id
          customerName
        }
        truckLoadId
        flag
        totalAmount
        totalCreditAmount
        conditionCode
        creditCode
      }
      isApproved
      isUrgent
      notes
      vessel {
        id
        vesselCode
      }
      shipper {
        id
        shipperName
      }
      vesselControl {
        id
        isLiquidated
      }
    }
    totalCount
  }
}
