mutation CONTACT_ALIAS_CREATE(
  $aliasName: String!
  $aliasDescription: String!
  $userId: BigInt
  $contacts: [ContactAliasPersonContactAliasIdFkeyContactAliasPersonContactCreateInput!]
) {
  createContactAlias(
    input: {
      contactAlias: {
        aliasDescription: $aliasDescription
        aliasName: $aliasName
        userId: $userId
        contactAliasPersonContactsUsingId: { create: $contacts }
      }
    }
  ) {
    clientMutationId
  }
}
