query CONTACT_ALIAS_DETAILS($id: BigInt!, $orderBy: [PersonContactsOrderBy!]) {
  contactAlias(id: $id) {
    aliasDescription
    aliasName
    id
    userId
    user {
      displayName
    }
    personContactsByContactAliasPersonContactAliasIdAndPersonContactId(
      orderBy: $orderBy
    ) {
      nodes {
        email
        firstName
        id
        lastName
        customerId
        customer {
          customerName
        }
        shipperId
        shipper {
          shipperName
        }
        warehouseId
        warehouse {
          warehouseName
        }
      }
      totalCount
    }
  }
}
