query CONTACT_ALIAS_LIST(
  $search: String
  $orderBy: [ContactAliasesOrderBy!]
  $userId: BigInt!
) {
  contactAliases(
    filter: {
      or: [{ userExists: false }, { userId: { equalTo: $userId } }]
      searchText: { includesInsensitive: $search }
    }
    orderBy: $orderBy
  ) {
    nodes {
      aliasName
      aliasDescription
      userId
      user {
        displayName
      }
      id
      personContactsByContactAliasPersonContactAliasIdAndPersonContactId {
        nodes {
          customerId
          customer {
            customerName
          }
          shipperId
          shipper {
            shipperName
          }
          warehouseId
          warehouse {
            warehouseName
          }
          email
          firstName
          id
          lastName
          workPhone
        }
        totalCount
      }
    }
    totalCount
  }
}
