query CONTACT_ALIAS_LIST($search: String, $orderBy: [ContactAliasesOrderBy!]) {
  contactAliases(
    filter: { searchText: { includesInsensitive: $search } }
    orderBy: $orderBy
  ) {
    nodes {
      aliasName
      aliasType
      aliasDescription
      id
      personContactsByContactAliasPersonContactAliasIdAndPersonContactId {
        nodes {
          customerId
          customer {
            customerName
          }
          shipperId
          shipper {
            shipperName
          }
          warehouseId
          warehouse {
            warehouseName
          }
          email
          firstName
          id
          lastName
          workPhone
        }
        totalCount
      }
    }
    totalCount
  }
}
