query CONTACT_ALIAS_LIST(
  $aliasType: [String!]
  $search: String
  $orderBy: [ContactAliasesOrderBy!]
) {
  contactAliases(
    filter: {
      aliasType: { in: $aliasType }
      searchText: { includesInsensitive: $search }
    }
    orderBy: $orderBy
  ) {
    nodes {
      aliasName
      aliasType
      id
      contactAliasPersonContactsByAliasId {
        totalCount
      }
    }
    totalCount
  }
}
