query REPACK_HEADER_DETAILS($repackCode: String!) {
  repackHeaders(filter: { repackCode: { like: $repackCode } }) {
    nodes {
      id
      repackCode
      runNumber
      boxesIn
      boxesOut
      weightIn
      weightOut
      whBagsOut
      whWeightIn
      whWeightOut
      whBoxesIn
      whBoxesOut
      repackDate
      repackStyleId
      warehouseId
      warehouse {
        id
        warehouseName
      }
      entryUserCode
      items {
        nodes {
          id
          repackCode
          runNumber
          palletId
          newPalletId
          boxesIn
          boxesOut
          notes
          pallet {
            containerId
            currentBoxQuantity
            growerId
            id
            locationId
            orderId
            palletId
            packDate
            shipped
            vesselCode
            shipper {
              id
              shipperName
            }
            product {
              id
              species {
                id
                speciesDescription
                commonSpecies {
                  id
                  palletWeight
                }
              }
            }
            packType {
              id
              packDescription
              commonPackType {
                id
                palletWeight
              }
            }
          }
        }
      }
      repackStyle {
        id
        styleName
        styleDescription
        commonPackType {
          id
          commonSpecies {
            id
          }
        }
      }
      notes
    }
  }
}
