query REPACK_HEADER_LIST(
  $repackStyleId: [String!]
  $warehouseId: [String!]
  $orderBy: [RepackHeadersOrderBy!]
  $search: [RepackHeaderFilter!]
  $repackDate: DateFilter!
) {
  repackHeaders(
    filter: {
      and: $search
      repackStyleId: { in: $repackStyleId }
      warehouseId: { in: $warehouseId }
      repackDate: $repackDate
    }
    orderBy: $orderBy
  ) {
    nodes {
      id
      count
      repackCode
      runNumber
      boxesIn
      boxesOut
      weightIn
      weightOut
      whBagsOut
      whWeightIn
      whWeightOut
      whBoxesIn
      whBoxesOut
      repackDate
      repackStyleId
      warehouseId
      warehouse {
        id
        warehouseName
      }
      entryUserCode
      repackStyle {
        id
        styleName
        styleDescription
      }
      repackQueue {
        orderId
        orders {
          totalCount
        }
        invoices {
          totalCount
        }
      }
      notes
    }
    totalCount
  }
}
