query REPACK_HEADER_LIST(
  $orderBy: [RepackHeadersOrderBy!]
  $search: [RepackHeaderFilter!]
  $repackDate: DateFilter!
) {
  repackHeaders(
    filter: { and: $search, repackDate: $repackDate }
    orderBy: $orderBy
  ) {
    nodes {
      id
      count
      repackCode
      runNumber
      boxesIn
      boxesOut
      weightIn
      weightOut
      whBagsOut
      whWeightIn
      whWeightOut
      whBoxesIn
      whBoxesOut
      repackDate
      repackStyleId
      warehouseId
      warehouse {
        id
        warehouseName
      }
      vessel {
        vesselCode
        vesselName
      }
      shipper {
        id
        shipperName
      }
      entryUserCode
      repackStyle {
        id
        styleName
        styleDescription
      }
      repackQueue {
        orderId
        orders {
          totalCount
        }
        invoices {
          totalCount
        }
      }
      notes
    }
    totalCount
  }
}
