query ORDER_ENTRY_DETAILS($orderId: BigFloat!) {
  orderEntries(condition: { orderId: $orderId }) {
    nodes {
      id
      orderId
      truckLoadId
      billingCustomer {
        id
        customerName
        postalState
      }
      salesUserCode
      salesUser {
        id
        personContact {
          id
          firstName
          lastName
          email
        }
      }
      submittedByUserCode
      submittedByUser {
        id
        personContact {
          id
          firstName
          lastName
          email
        }
      }
      reviewUserCode
      reviewDate
      reviewUser {
        id
        personContact {
          id
          firstName
          lastName
        }
      }
      customerPo
      fob
      fobDate
      deliveredDate
      orderDate
      orderEntryItems {
        nodes {
          id
          orderEntryId
          lineId
          palletCount
          unitSellPrice
          deliveryCharge
          locationId
          vesselCode
          shipperId
          species
          variety
          size
          packType
          plu
          label
          countryOfOrigin
          boxCount
          palletWeight
          notes
          vessel {
            id
            vesselCode
            vesselName
            isPre
          }
          shipper {
            id
            shipperName
          }
          warehouse {
            id
            warehouseName
          }
          orderEntryReviewItems {
            nodes {
              id
              orderEntryItemId
              locationId
              vesselCode
              shipperId
              species
              variety
              size
              packType
              plu
              label
              countryOfOrigin
              palletCount
              boxCount
              palletWeight
              vessel {
                id
                vesselCode
                vesselName
              }
              shipper {
                id
                shipperName
              }
              warehouse {
                id
                warehouseName
              }
            }
          }
        }
      }
    }
  }
}
