query ORDER_ENTRY_DETAILS($orderId: BigFloat!) {
  orderEntries(condition: { orderId: $orderId }) {
    nodes {
      id
      orderId
      truckLoadId
      billingCustomer {
        id
        customerName
      }
      salesUserCode
      salesUser {
        id
        personContact {
          id
          firstName
          lastName
          email
        }
      }
      reviewUserCode
      reviewDate
      reviewUser {
        id
        personContact {
          id
          firstName
          lastName
        }
      }
      customerPo
      fob
      fobDate
      orderDate
      orderEntryItems {
        nodes {
          id
          orderEntryId
          lineId
          palletCount
          unitSellPrice
          deliveryCharge
          locationId
          vesselCode
          shipperId
          species
          variety
          size
          packType
          plu
          label
          reviewLocationId
          reviewVesselCode
          reviewShipperId
          reviewSpecies
          reviewVariety
          reviewSize
          reviewPackType
          reviewPlu
          reviewLabel
          notes
          vessel {
            id
            vesselCode
            vesselName
          }
          shipper {
            id
            shipperName
          }
          warehouse {
            id
            warehouseName
          }
          reviewVessel {
            id
            vesselCode
            vesselName
          }
          reviewShipper {
            id
            shipperName
          }
          reviewWarehouse {
            id
            warehouseName
          }
        }
      }
    }
  }
}
