query ORDER_ENTRY_LIST(
  $billingCustomerId: [String!]
  $salesUserCode: [String!]
  $orderBy: [OrderEntriesOrderBy!]
  $search: [OrderEntryFilter!]
  $endDate: Date
  $startDate: Date
) {
  orderEntries(
    condition: { reviewUserCode: null }
    filter: {
      and: $search
      billingCustomerId: { in: $billingCustomerId }
      salesUserCode: { in: $salesUserCode }
      or: {
        fobDate: {
          greaterThanOrEqualTo: $startDate
          lessThanOrEqualTo: $endDate
        }
      }
    }
    orderBy: $orderBy
  ) {
    nodes {
      id
      orderId
      truckLoadId
      billingCustomer {
        id
        customerName
      }
      salesUser {
        id
        personContact {
          id
          firstName
          lastName
        }
      }
      reviewUser {
        id
        personContact {
          id
          firstName
          lastName
        }
      }
      customerPo
      fobDate
      reviewUserCode
    }
    totalCount
  }
}
