query INTERNAL_CONTACT_LIST(
  $search: String
  $orderBy: [PersonContactsOrderBy!]
) {
  personContacts(
    condition: { isInternal: true }
    filter: { searchText: { includesInsensitive: $search } }
    orderBy: $orderBy
  ) {
    nodes {
      id
      firstName
      lastName
      email
      workPhone
      workExtension
    }
    totalCount
  }
}
