query COMPANY_DETAILS($id: String!) {
  company(id: $id) {
    companyName
    companyType
    logoSrc
    notes
    primaryContact {
      contactName
      email
    }
    website
    personContacts {
      nodes {
        firstName
        lastName
        id
      }
    }
  }
}
