query COMPANY_LIST(
  $orderBy: [CompaniesOrderBy!]
  $search: String
  $companyType: String
) {
  companies(
    condition: { companyType: $companyType }
    filter: { searchText: { includesInsensitive: $search } }
    orderBy: $orderBy
  ) {
    nodes {
      companyName
      companyType
      id
      logoSrc
      notes
      website
      primaryContact {
        contactName
        email
      }
    }
    totalCount
  }
}
