query SHIPPER_PROJECTION_LIST(
  $arrivalPort: String!
  $endDate: Datetime!
  $startDate: Datetime!
  $orderBy: [ShipperProjectionsOrderBy!]
  $search: [ShipperProjectionFilter!]
  $shipperId: [String!]
) {
  shipperProjections(
    filter: {
      and: $search
      submittedAt: {
        greaterThanOrEqualTo: $startDate
        lessThanOrEqualTo: $endDate
      }
      shipperId: { in: $shipperId }
      shipperProjectionVesselInfosByProjectionId: {
        some: { arrivalPort: { equalTo: $arrivalPort } }
      }
    }
    orderBy: $orderBy
  ) {
    nodes {
      id
      submittedAt
      approvedAt
      rejectedAt
      jvComments
      shipperComments
      reviewStatus
      shipper {
        id
        shipperName
      }
      shipperProjectionVesselInfosByProjectionId {
        nodes {
          shipperProjectionEntriesByVesselInfoId {
            nodes {
              palletCount
              product {
                species
              }
            }
          }
        }
      }
      totalPallets
    }
    totalCount
  }
}
