query SHIPPER_PROJECTION_PRODUCT_LIST($shipperId: String) {
  shipperProjectionProducts(condition: { shipperId: $shipperId }) {
    nodes {
      id
      packType
      size
      species
      variety
      customerValue
      commonSpeciesId
      commonVarietyId
      commonSizeId
      commonPackTypeId
      customerId
      customer {
        id
        customerName
      }
    }
  }
}
