query SHIPPER_PROJECTION_VESSEL_INFO_LIST(
  $arrivalPort: String!
  $shipperId: String
  $endDate: Date!
  $startDate: Date!
  $endDatetime: Datetime!
  $startDatetime: Datetime!
) {
  shipperProjectionVesselInfos(
    condition: { arrivalPort: $arrivalPort, shipperId: $shipperId }
    filter: {
      departureDate: {
        greaterThanOrEqualTo: $startDate
        lessThanOrEqualTo: $endDate
      }
    }
    orderBy: DEPARTURE_DATE_ASC
  ) {
    nodes {
      arrivalDate
      departureDate
      vesselStatus
      arrivalPort
      id
      vesselName
      vessel {
        id
        shipperProjectionVesselInfosByVesselId {
          nodes {
            id
            vesselName
          }
        }
      }
      vesselId
      shipperId
      shipper {
        id
        shipperProjections(
          filter: {
            submittedAt: {
              greaterThanOrEqualTo: $startDatetime
              lessThanOrEqualTo: $endDatetime
            }
          }
        ) {
          nodes {
            id
            submittedAt
          }
        }
      }
      vessel {
        id
        shipper {
          shipperName
          id
        }
      }
      projection {
        id
        submittedAt
        approvedAt
        rejectedAt
        jvComments
        shipperComments
        reviewStatus
        shipper {
          id
          shipperName
        }
      }
      shipperProjectionEntriesByVesselInfoId {
        nodes {
          id
          palletCount
          productId
          vesselInfoId
          product {
            id
            packType
            plu
            size
            species
            variety
            commonSpeciesId
            commonSpecies {
              id
              speciesName
              uiColor
              commonSpeciesTags {
                nodes {
                  commonSpeciesId
                  nodeId
                  tagText
                }
              }
            }
            commonVarietyId
            commonVariety {
              id
              varietyName
              uiColor
              commonVarietyTags {
                nodes {
                  tagText
                  nodeId
                  commonVarietyId
                }
              }
            }
            commonSizeId
            commonSize {
              id
              sizeName
              commonSizeTags {
                nodes {
                  commonSizeId
                  nodeId
                  tagText
                }
              }
            }
            commonPackTypeId
            commonPackType {
              id
              packTypeName
              commonPackTypeTags {
                nodes {
                  commonPackTypeId
                  nodeId
                  tagText
                }
              }
            }
          }
        }
      }
    }
  }
}
