query INVOICE_HEADER_DETAILS($orderId: BigFloat!) {
  invoiceHeaders(condition: { orderId: $orderId }) {
    nodes {
      orderId
      backOrderId
      truckLoadId
      truckLoad {
        loadId
        fob
      }
      shipWarehouseId
      invoiceId
      salesUserCode
      customerPo
      invoiceDate
      actualShipDate
      expectedShipDate
      amountOwed
      flag
      paidCode
      vendor {
        id
        vendorName
      }
      billingCustomer {
        id
        customerName
      }
      netAmountDue
      totalAmount
      totalAmountsByVesselAndShipper {
        nodes
      }
      payments {
        nodes {
          id
          checkNumber
          transactionCode
          transactionType
          netAmountDue
          notes
        }
      }
      repackQueues {
        nodes {
          id
          repackCode
          repackDate
          repackStyle {
            id
            styleDescription
          }
          warehouse {
            id
            warehouseName
          }
          palletCount
          repackHeaders {
            nodes {
              id
              boxesIn
              boxesOut
              weightIn
              weightOut
            }
          }
        }
      }
      itemHistories {
        nodes {
          id
          orderId
          backOrderId
          lineId
          unitSellPrice
          sequenceId
          palletId
          pickedQty
          conditionCode
          creditCode
          priceAdjustment
          deliveryCharge
          freightAdjustment
          pallet {
            backOrderId
            id
            jvLotNumber
            locationId
            orderId
            packDate
            palletId
            product {
              id
              species {
                id
                speciesDescription
              }
              variety {
                id
                varietyDescription
              }
            }
            packType {
              id
              packDescription
              pluUpcCode
              label {
                id
                labelName
                labelCode
              }
            }
            sizes {
              nodes {
                id
                combineDescription
                jvDescription
              }
            }
            shipped
            shipper {
              id
              shipperName
            }
            vessel {
              coast
              dischargeDate
              id
              vesselCode
            }
            warehouse {
              id
              warehouseName
            }
          }
        }
      }
      items {
        nodes {
          id
          orderId
          backOrderId
          lineId
          unitSellPrice
          sequenceId
          pickedQty
          palletStatus
          conditionCode
          creditCode
          repackCode
          priceAdjustment
          deliveryCharge
          freightAdjustment
          creditAmount
          brokerageAmount
          volumeDiscountAmount
          layerMult
          flag
          notes
          pallet {
            backOrderId
            id
            jvLotNumber
            locationId
            orderId
            packDate
            palletId
            product {
              id
              species {
                id
                speciesDescription
              }
              variety {
                id
                varietyDescription
              }
            }
            packType {
              id
              packDescription
              pluUpcCode
              label {
                id
                labelName
                labelCode
              }
            }
            sizes {
              nodes {
                id
                combineDescription
                jvDescription
              }
            }
            shipped
            shipper {
              id
              shipperName
            }
            vessel {
              coast
              dischargeDate
              id
              vesselCode
            }
            warehouse {
              id
              warehouseName
            }
          }
        }
      }
      salesUser {
        id
        personContact {
          id
          firstName
          lastName
        }
        userCode
      }
      rejectedInvoices {
        nodes {
          orderId
          amountOwed
          netAmountDue
          truckLoadId
          items {
            nodes {
              id
              orderId
              backOrderId
              lineId
              unitSellPrice
              sequenceId
              pickedQty
              palletStatus
              conditionCode
              creditCode
              repackCode
              priceAdjustment
              deliveryCharge
              freightAdjustment
              creditAmount
              brokerageAmount
              layerMult
              flag
              notes
              pallet {
                backOrderId
                id
                jvLotNumber
                locationId
                orderId
                packDate
                palletId
                product {
                  id
                  species {
                    id
                    speciesDescription
                  }
                  variety {
                    id
                    varietyDescription
                  }
                }
                packType {
                  id
                  packDescription
                  pluUpcCode
                  label {
                    id
                    labelName
                    labelCode
                  }
                }
                sizes {
                  nodes {
                    id
                    combineDescription
                    jvDescription
                  }
                }
                shipped
                shipper {
                  id
                  shipperName
                }
                vessel {
                  coast
                  dischargeDate
                  id
                  vesselCode
                }
                warehouse {
                  id
                  warehouseName
                }
              }
            }
          }
          totalAmountsByVesselAndShipper {
            nodes
          }
        }
      }
      originalInvoice {
        orderId
        amountOwed
        netAmountDue
        truckLoadId
        items {
          nodes {
            id
            orderId
            backOrderId
            lineId
            unitSellPrice
            sequenceId
            pickedQty
            palletStatus
            conditionCode
            creditCode
            repackCode
            priceAdjustment
            deliveryCharge
            freightAdjustment
            creditAmount
            brokerageAmount
            layerMult
            flag
            notes
            pallet {
              backOrderId
              id
              jvLotNumber
              locationId
              orderId
              packDate
              palletId
              product {
                id
                species {
                  id
                  speciesDescription
                }
                variety {
                  id
                  varietyDescription
                }
              }
              packType {
                id
                packDescription
                pluUpcCode
                label {
                  id
                  labelName
                  labelCode
                }
              }
              sizes {
                nodes {
                  id
                  combineDescription
                  jvDescription
                }
              }
              shipped
              shipper {
                id
                shipperName
              }
              vessel {
                coast
                dischargeDate
                id
                vesselCode
              }
              warehouse {
                id
                warehouseName
              }
            }
          }
        }
        totalAmountsByVesselAndShipper {
          nodes
        }
      }
      splitInvoices {
        nodes {
          orderId
          amountOwed
          netAmountDue
          truckLoadId
          items {
            nodes {
              id
              orderId
              backOrderId
              lineId
              unitSellPrice
              sequenceId
              pickedQty
              palletStatus
              conditionCode
              creditCode
              repackCode
              priceAdjustment
              deliveryCharge
              freightAdjustment
              creditAmount
              brokerageAmount
              layerMult
              flag
              notes
              pallet {
                backOrderId
                id
                jvLotNumber
                locationId
                orderId
                packDate
                palletId
                product {
                  id
                  species {
                    id
                    speciesDescription
                  }
                  variety {
                    id
                    varietyDescription
                  }
                }
                packType {
                  id
                  packDescription
                  pluUpcCode
                  label {
                    id
                    labelName
                    labelCode
                  }
                }
                sizes {
                  nodes {
                    id
                    combineDescription
                    jvDescription
                  }
                }
                shipped
                shipper {
                  id
                  shipperName
                }
                vessel {
                  coast
                  dischargeDate
                  id
                  vesselCode
                }
                warehouse {
                  id
                  warehouseName
                }
              }
            }
          }
          totalAmountsByVesselAndShipper {
            nodes
          }
        }
      }
    }
  }
}
