query INVOICE_HEADER_LIST(
  $billingCustomerId: [String!]
  $salesUserCode: [String!]
  $orderBy: [InvoiceHeadersOrderBy!]
  $search: [InvoiceHeaderFilter!]
  $endDate: Date
  $startDate: Date
) {
  invoiceHeaders(
    filter: {
      and: $search
      billingCustomerId: { in: $billingCustomerId }
      salesUserCode: { in: $salesUserCode }
      or: {
        actualShipDate: {
          greaterThanOrEqualTo: $startDate
          lessThanOrEqualTo: $endDate
        }
      }
    }
    orderBy: $orderBy
  ) {
    nodes {
      orderId
      backOrderId
      truckLoadId
      shipWarehouseId
      invoiceId
      salesUserCode
      paidCode
      customerPo
      invoiceDate
      totalAmount
      actualShipDate
      expectedShipDate
      flag
      amountOwed
      vendor {
        id
        vendorName
      }
      billingCustomer {
        id
        city
        customerName
      }
      items {
        nodes {
          id
          orderId
          backOrderId
          lineId
          pickedQty
          unitSellPrice
          flag
          pallet {
            backOrderId
            id
            jvLotNumber
            locationId
            orderId
            packDate
            palletId
            product {
              id
              species {
                id
                speciesDescription
              }
              variety {
                id
                varietyDescription
              }
            }
            packType {
              id
              packDescription
              pluUpcCode
              label {
                id
                labelName
                labelCode
              }
            }
            sizes {
              nodes {
                id
                combineDescription
                jvDescription
              }
            }
            shipped
            shipper {
              id
              shipperName
            }
            vessel {
              coast
              dischargeDate
              id
              isPre
              vesselCode
            }
            warehouse {
              id
              warehouseName
            }
          }
        }
      }
      salesUser {
        id
        personContact {
          id
          firstName
          lastName
        }
        userCode
      }
    }
    totalCount
  }
}
