query PALLET_DETAILS($palletId: String!) {
  pallets(condition: { palletId: $palletId }) {
    nodes {
      age
      backOrderId
      billOfLading
      containerId
      currentBoxQuantity
      dateTransferredToStorage
      deck
      filler
      growerId
      hatch
      id
      invoices {
        nodes {
          id
          orderId
          invoiceId
          truckLoadId
          billingCustomer {
            id
            customerName
          }
          invoiceDate
          customerPo
          salesUser {
            personContact {
              firstName
            }
          }
        }
      }
      repacks {
        nodes {
          id
          repackCode
          runNumber
          repackDate
          repackStyleId
          boxesIn
          boxesOut
        }
      }
      jvLotNumber
      locationId
      oldPackCode
      orderId
      originalLocation {
        id
        warehouseName
      }
      packDate
      palletId
      palletSections {
        nodes {
          boxQuantity
          growerId
          id
          packDate
          sizeId
          palletId
          variety {
            id
            varietyDescription
          }
        }
      }
      product {
        id
        species {
          id
          speciesDescription
        }
        variety {
          id
          varietyDescription
        }
      }
      packType {
        id
        packDescription
        pluUpcCode
        label {
          id
          labelName
        }
      }
      sizes {
        nodes {
          id
          combineDescription
          jvDescription
        }
      }
      psaArrivalReport {
        id
      }
      receivedBoxQuantity
      returnedBoxQuantity
      room
      row
      section
      shipped
      shipper {
        id
        shipperName
      }
      temperatureRecording
      vessel {
        coast
        dischargeDate
        id
        vesselCode
        vesselName
      }
      volumeDiscountCode
      warehouse {
        id
        warehouseName
      }
    }
  }
}
