query PALLET_DETAILS($palletId: String!) {
  pallets(condition: { palletId: $palletId }) {
    nodes {
      age
      backOrderId
      billOfLading
      containerId
      currentBoxQuantity
      dateTransferredToStorage
      deck
      filler
      growerId
      hatch
      id
      jvLotNumber
      locationId
      oldPackCode
      orderId
      originalLocation {
        id
        warehouseName
      }
      packDate
      palletId
      palletSections {
        nodes {
          boxQuantity
          growerId
          id
          packDate
          sizeId
          palletId
          variety {
            id
            varietyDescription
          }
        }
      }
      product {
        packType {
          id
          packDescription
          pluUpcCode
          label {
            id
            labelName
          }
        }
        id
        sizes {
          nodes {
            id
            combineDescription
            jvDescription
          }
        }
        species {
          id
          speciesDescription
        }
        variety {
          id
          varietyDescription
        }
      }
      psaArrivalReport {
        id
      }
      receivedBoxQuantity
      returnedBoxQuantity
      room
      row
      section
      shipped
      shipper {
        id
        shipperName
      }
      temperatureRecording
      vessel {
        coast
        dischargeDate
        id
        vesselCode
        vesselName
      }
      volumeDiscountCode
      warehouse {
        id
        warehouseName
      }
    }
  }
}
