query COMMON_VARIETY($id: BigInt!) {
  commonVariety(id: $id) {
    commonSpecies {
      id
      speciesName
      commonCategory {
        id
        categoryName
      }
      commonVarieties {
        nodes {
          id
          varietyName
          commonVarietyTags {
            nodes {
              tagText
              nodeId
              commonVarietyId
            }
          }
        }
      }
    }
    id
    defaultInvSortKey
    productVarietyId
    productVarietiesByCommonVarietyProductVarietyCommonVarietyIdAndProductVarietyId {
      nodes {
        id
        varietyDescription
      }
    }
    uiColor
    varietyDescription
    varietyName
    commonVarietyTags {
      nodes {
        tagText
        nodeId
        commonVarietyId
      }
    }
  }
}
