query CONTACT_GROUP_LIST(
  $search: [ContactGroupFilter!]
  $orderBy: [ContactGroupsOrderBy!]
  $userId: BigInt!
) {
  contactGroups(
    filter: {
      and: $search
      or: [{ userExists: false }, { userId: { equalTo: $userId } }]
    }
    orderBy: $orderBy
  ) {
    nodes {
      groupName
      groupDescription
      userId
      user {
        displayName
      }
      id
      personContactsByContactGroupPersonContactGroupIdAndPersonContactId {
        nodes {
          customersByCustomerPersonContactPersonContactIdAndCustomerId {
            nodes {
              customerName
              id
            }
          }
          shippersByShipperPersonContactPersonContactIdAndShipperId {
            nodes {
              shipperName
              id
            }
          }
          warehousesByWarehousePersonContactPersonContactIdAndWarehouseId {
            nodes {
              warehouseName
              id
            }
          }
          email
          firstName
          id
          lastName
          workPhone
        }
        totalCount
      }
    }
    totalCount
  }
}
