mutation SHIPPER_PROJECTION_ENTRY_CREATE(
  $shipperProjectionEntry: ShipperProjectionEntryInput!
) {
  createShipperProjectionEntry(
    input: { shipperProjectionEntry: $shipperProjectionEntry }
  ) {
    shipperProjectionEntry {
      id
    }
  }
}
