mutation SHIPPER_PROJECTION_UPSERT(
  $shipperProjection: ShipperProjectionInput!
) {
  upsertShipperProjection(input: { shipperProjection: $shipperProjection }) {
    shipperProjection {
      id
    }
  }
}
