mutation SHIPPER_PROJECTION_PRODUCT_UPSERT(
  $shipperProjectionProducts: [ShipperProjectionProductInput]!
) {
  bulkUpsertShipperProjectionProduct(
    input: { products: $shipperProjectionProducts }
  ) {
    shipperProjectionProducts {
      id
      species
      variety
      size
      packType
      plu
      customerValue
    }
  }
}
