mutation BULK_UPSERT_SHIPPER_PROJECTION_VESSEL(
  $shipperProjectionVessels: [ShipperProjectionVesselInput]!
) {
  bulkUpsertShipperProjectionVessel(
    input: { vessels: $shipperProjectionVessels }
  ) {
    shipperProjectionVessels {
      id
    }
  }
}
