mutation BULK_UPSERT_SHIPPER_PROGRAM($shipperPrograms: [ShipperProgramInput]!) {
  bulkUpsertShipperProgram(input: { programs: $shipperPrograms }) {
    shipperPrograms {
      id
      commonSpeciesId
      commonVarietyId
      commonSizeId
      commonPackTypeId
      plu
      customerId
    }
  }
}
