query SHIPPER_PROGRAM_LIST(
  $arrivalPort: String!
  $endDate: Date!
  $startDate: Date!
  $shipperId: String
) {
  shipperPrograms(
    condition: { arrivalPort: $arrivalPort, shipperId: $shipperId }
    filter: {
      shipperProgramEntries: {
        some: {
          programDate: {
            greaterThanOrEqualTo: $startDate
            lessThanOrEqualTo: $endDate
          }
        }
      }
    }
  ) {
    nodes {
      arrivalPort
      commonPackType {
        id
        packTypeName
      }
      commonPackTypeId
      commonSize {
        id
        sizeName
      }
      commonSizeId
      commonSpecies {
        id
        speciesName
        uiColor
      }
      commonSpeciesId
      commonVariety {
        id
        uiColor
        varietyName
      }
      commonVarietyId
      id
      plu
      shipperId
      shipper {
        id
        shipperName
      }
      shipperProgramEntries {
        nodes {
          id
          notes
          palletCount
          programDate
        }
      }
    }
  }
}
