query ORDER_MASTER_DETAILS($orderId: BigFloat!) {
  orderMasters(condition: { orderId: $orderId }) {
    nodes {
      actualShipDate
      backOrderId
      billingCustomer {
        id
        customerName
      }
      comments {
        nodes {
          id
          backOrderId
          lineId
          printCode
          notes
        }
      }
      customerPo
      deliveryZone
      entryDate
      entryUserCode
      entryUser {
        id
        personContact {
          id
          firstName
          lastName
        }
      }
      expectedShipDate
      fob
      id
      items {
        nodes {
          backOrderId
          boxCount
          deliveryCharge
          id
          inventoryItem {
            id
            vessel {
              id
              dischargeDate
              vesselCode
              vesselName
              isPre
            }
            shipper {
              id
              shipperName
            }
            coast
            plu
            product {
              id
              species {
                id
                speciesDescription
              }
              variety {
                id
                varietyDescription
              }
              sizes {
                nodes {
                  id
                  combineDescription
                  jvDescription
                }
              }
              packType {
                id
                label {
                  id
                  labelName
                }
                packDescription
              }
            }
          }
          isBundle
          itemStatus
          lineId
          orderId
          order {
            id
            actualShipDate
            expectedShipDate
          }
          palletCount
          notes
          unitSellPrice
          locationId
          shipperId
          specialLotNumber
        }
      }
      truckLoad {
        id
        loadId
        changeFlag
      }
      vendor {
        id
        vendorName
      }
      loadStatus
      loadLocation
      notes
      orderDate
      orderId
      orderStatus
      repackQueues {
        nodes {
          id
          repackCode
          repackDate
          repackStyle {
            id
            styleDescription
          }
          warehouse {
            id
            warehouseName
          }
          palletCount
          repackHeaders {
            nodes {
              id
              boxesIn
              boxesOut
              weightIn
              weightOut
            }
          }
        }
      }
      salesUser {
        id
        personContact {
          id
          firstName
          lastName
        }
      }
      shipWarehouse {
        id
        warehouseName
      }
      shippingCustomer {
        id
        customerName
      }
    }
  }
}
