query ORDER_MASTER_LIST(
  $billingCustomerId: [String!]
  $salesUserCode: [String!]
  $orderBy: [OrderMastersOrderBy!]
  $search: [OrderMasterFilter!]
  $endDate: Date
  $startDate: Date
) {
  orderMasters(
    filter: {
      and: $search
      billingCustomerId: { in: $billingCustomerId }
      salesUserCode: { in: $salesUserCode }
      or: {
        expectedShipDate: {
          greaterThanOrEqualTo: $startDate
          lessThanOrEqualTo: $endDate
        }
      }
    }
    orderBy: $orderBy
  ) {
    nodes {
      backOrderId
      actualShipDate
      expectedShipDate
      id
      orderDate
      orderId
      orderStatus
      customerPo
      truckLoadId
      truckLoad {
        shipDate
      }
      billingCustomer {
        id
        customerName
      }
      items {
        nodes {
          orderId
          backOrderId
          boxCount
          deliveryCharge
          id
          inventoryItem {
            id
            country {
              id
              countryName
            }
            vessel {
              id
              vesselCode
              vesselName
              isPre
              dischargeDate
            }
            coast
            shipper {
              id
              shipperName
            }
            warehouse {
              id
              warehouseName
            }
            jvLotNumber
            plu
            product {
              id
              species {
                id
                speciesDescription
              }
              variety {
                id
                varietyDescription
              }
            }
            sizes {
              nodes {
                id
                combineDescription
                jvDescription
              }
            }
            packType {
              packDescription
              id
              label {
                id
                labelCode
                labelName
              }
            }
          }
          locationId
          shipperId
          specialLotNumber
          palletCount
          unitSellPrice
          order {
            id
            actualShipDate
            expectedShipDate
            salesUserCode
            billingCustomer {
              id
              customerName
            }
          }
        }
      }
      salesUser {
        id
        personContact {
          id
          firstName
          lastName
        }
        userCode
      }
      entryUserCode
      entryUser {
        id
        personContact {
          id
          firstName
          lastName
        }
      }
    }
    totalCount
  }
}
