query PSA_ARRIVAL_INSPECTION_DETAILS_COM_VAR_LIST(
  $id: BigInt!
  $commodity: String!
  $variety: String!
) {
  psaArrivalReport(id: $id) {
    id
    commodityList
    varietyList(com: $commodity)
    avgNetWeight(vari: $variety)
    avgConditionByVariety(vari: $variety)
    avgQualityByVariety(vari: $variety)
    avgBrix(vari: $variety)
    avgGrapeBunchesPerBox(vari: $variety)
    avgGrapeBrixMin(vari: $variety)
    avgGrapeBrixMost(vari: $variety)
    avgGrapeBrixMax(vari: $variety)
    avgCitrusDiameterMinMm(vari: $variety)
    avgCitrusDiameterMaxMm(vari: $variety)
    avgCitrusDiameterMostMm(vari: $variety)
    avgStoneFruitPressuresMin(vari: $variety)
    avgStoneFruitPressuresMax(vari: $variety)
    avgStoneFruitPressuresAvg(vari: $variety)
    avgPomegranateBrixMin(vari: $variety)
    avgPomegranateBrixMost(vari: $variety)
    avgPomegranateBrixMax(vari: $variety)
    avgPersimmonPressuresMin(vari: $variety)
    avgPersimmonPressuresMax(vari: $variety)
    avgPersimmonPressuresAvg(vari: $variety)
    avgPearPressuresMin(vari: $variety)
    avgPearPressuresMax(vari: $variety)
    avgPearPressuresAvg(vari: $variety)
    avgLemonDiameterMinMm(vari: $variety)
    avgLemonDiameterMaxMm(vari: $variety)
    avgLemonDiameterMostMm(vari: $variety)
    avgCherrySizeMin(vari: $variety)
    avgCherrySizeMax(vari: $variety)
    avgCherrySizeMost(vari: $variety)
    avgApplePressuresMin(vari: $variety)
    avgApplePressuresMax(vari: $variety)
    avgApplePressuresAvg(vari: $variety)
    grapePallets(filter: { variety: { equalTo: $variety } }) {
      nodes {
        palletId
      }
      totalCount
    }
    citrusPallets(filter: { variety: { equalTo: $variety } }) {
      nodes {
        palletId
      }
      totalCount
    }
    stoneFruitPallets(filter: { variety: { equalTo: $variety } }) {
      nodes {
        palletId
      }
      totalCount
    }
    pomegranatePallets(filter: { variety: { equalTo: $variety } }) {
      nodes {
        palletId
      }
      totalCount
    }
    persimmonPallets(filter: { variety: { equalTo: $variety } }) {
      nodes {
        palletId
      }
      totalCount
    }
    pearPallets(filter: { variety: { equalTo: $variety } }) {
      nodes {
        palletId
      }
      totalCount
    }
    lemonPallets(filter: { variety: { equalTo: $variety } }) {
      nodes {
        palletId
      }
      totalCount
    }
    cherryPallets(filter: { variety: { equalTo: $variety } }) {
      nodes {
        palletId
      }
      totalCount
    }
    applePallets(filter: { variety: { equalTo: $variety } }) {
      nodes {
        palletId
      }
      totalCount
    }
  }
}
