query PSA_ARRIVAL_INSPECTION_DETAILS($id: BigInt!) {
  psaArrivalReport(id: $id) {
    arrivalCode
    arrivalName
    exporterId
    exporterName
    id
    locationName
    reportDate
    reportUrl
    pictures {
      nodes {
        id
        imageUrl
        palletId
        pictureDescription
        productCode
        varietyName
      }
    }
    avgGrapeNetWeight
    avgGrapeCondition
    avgGrapeBunchesPerBox
    avgGrapeBrixMin
    avgGrapeBrixMost
    avgGrapeBrixMax
    avgGrapeQuality
  }
}
