query PSA_ARRIVAL_INSPECTIONS_LIST(
  $endDate: Date
  $orderBy: [PsaArrivalReportsOrderBy!]
  $search: [PsaArrivalReportFilter!]
  $startDate: Date
) {
  psaArrivalReports(
    filter: {
      and: $search
      or: {
        reportDate: {
          greaterThanOrEqualTo: $startDate
          lessThanOrEqualTo: $endDate
        }
      }
    }
    orderBy: $orderBy
  ) {
    nodes {
      arrivalCode
      arrivalName
      exporterId
      exporterName
      id
      locationName
      reportDate
      qualityRange
      conditionRange
      shipper {
        id
        shipperName
      }
      pictures(first: 5) {
        nodes {
          id
          imageUrl
          palletId
          pictureDescription
          productCode
          varietyName
        }
      }
    }
    totalCount
  }
}
