query PSA_ARRIVAL_PALLET_DETAILS($id: BigInt!) {
  psaGrapePallet(id: $id) {
    id
    location
    arrival
    importerName
    exporterName
    commodity
    productCode
    variety
    inspDate
    quantity
    hatch
    deck
    containerId
    fumigation
    labelCode
    inspLocation
    importerCode
    lotCode
    inspLot
    palletId
    growerCode
    inspGrowerCode
    packDate
    inspPackDate
    size
    inspSize
    packCode
    packDescription
    secondaryDescription
    grade
    inspPackCode
    count
    plu
    pluPct
    countryOfOrigin
    upc
    weight
    underweightMin
    underweightMax
    weighedUnits
    underweightUnits
    underweightPct
    pulpTemp
    opening
    autoOpening
    bunches
    sizeMin
    sizeMax
    sizeMost
    undersizeBunchesCount
    autoUndersizeBerriesBunches
    undersizeBerriesPct
    colorMin
    colorMax
    colorMost
    colorConsistency
    autoColorConsistency
    sunburnBunches
    autoSunburnBunches
    sunburnPct
    sunburnBunchesDeg
    bunchConformation
    autoBunchConformation
    stragglyBunches
    stragglyPct
    smallBunches
    russetMarksBunches
    russetMarksPct
    autoRussetMarksPct
    dustPct
    autoDustPct
    residuesPct
    autoResiduesPct
    tightBunches
    autoTightBunches
    bruisingBunches
    autoBruisingBunches
    bruisingPct
    bruisingDeg
    stemDehydrationPct
    autoStemDehydrationPct
    stemDehydrationDeg
    berryCondition
    autoBerryCondition
    h2OBerries
    autoH2OBerries
    so2DamagePct
    autoSo2DamagePct
    so2DamageDeg
    weakBunches
    autoWeakBunches
    splitsHairlinePct
    autoSplitsHairlinePct
    splitsWetCrushPct
    autoSplitsWetCrushPct
    splitsDryPct
    autoSplitsDryPct
    intDisc
    autoIntDisc
    intDiscDeg
    decayMoldBerries
    autoDecayMoldBerries
    decaySlipskinBerries
    autoDecaySlipskinBerries
    decayNestBerries
    autoDecayNestBerries
    decayNestDeg
    shatterPct
    autoShatterPct
    brixMin
    brixMax
    brixMost
    overallQuality
    autoOverallQuality
    overallCondition
    autoOverallCondition
    comment1
    comment2
    inspectionType
    shortInsp
    fixedWeight
    pictures {
      nodes {
        id
        imageUrl
        palletId
        pictureDescription
        productCode
        varietyName
      }
    }
  }
}
