query VESSEL_DETAILS($vesselCode: String!, $isPre: Boolean!) {
  vessels(condition: { vesselCode: $vesselCode, isPre: $isPre }) {
    nodes {
      arrivalDate
      arrivalPort
      coast
      countryId
      country {
        id
        countryName
      }
      departureDate
      dischargeDate
      id
      invFlag
      inventoryItems {
        nodes {
          coast
          country {
            id
            countryName
          }
          id
          pallets {
            totalCount
          }
          palletsAvailable
          palletsCommitted
          palletsReceived
          palletsShipped
          palletsOnHand
          plu
          product {
            id
            species {
              id
              speciesDescription
            }
            variety {
              id
              varietyDescription
            }
          }
          sizes(first: 1) {
            nodes {
              id
              combineDescription
              jvDescription
            }
          }
          packType {
            packDescription
            id
            label {
              labelName
            }
          }
          shipper {
            shipperName
            id
          }
          vessel {
            id
            dischargeDate
            vesselCode
            vesselName
            isPre
          }
          warehouse {
            id
            warehouseName
          }
        }
      }
      shipperProjectionVessels {
        nodes {
          shipperProjectionVesselInfosByVesselId {
            nodes {
              arrivalDate
              departureDate
              vesselStatus
              arrivalPort
              id
              vesselName
              vessel {
                id
                vesselId
                shipperProjectionVesselInfosByVesselId {
                  nodes {
                    id
                    vesselName
                  }
                }
              }
              vesselId
              shipperId
              shipper {
                id
                shipperName
                country {
                  id
                  countryName
                }
                shipperProjections {
                  nodes {
                    id
                    submittedAt
                  }
                }
              }
              vessel {
                id
                shipper {
                  shipperName
                  id
                }
              }
              projection {
                id
                submittedAt
                approvedAt
                rejectedAt
                jvComments
                shipperComments
                reviewStatus
                shipper {
                  id
                  shipperName
                }
              }
              shipperProjectionEntriesByVesselInfoId {
                nodes {
                  id
                  palletCount
                  productId
                  vesselInfoId
                  product {
                    id
                    packType
                    plu
                    size
                    species
                    variety
                    customerValue
                    customer {
                      id
                      customerName
                    }
                    commonSpeciesId
                    commonSpecies {
                      id
                      speciesName
                      uiColor
                      productSpeciesId
                      productSpecies {
                        id
                        speciesDescription
                      }
                      commonSpeciesTags {
                        nodes {
                          commonSpeciesId
                          nodeId
                          tagText
                        }
                      }
                    }
                    commonVarietyId
                    commonVariety {
                      id
                      varietyName
                      uiColor
                      productVarietyId
                      productVariety {
                        id
                        varietyDescription
                      }
                      commonVarietyTags {
                        nodes {
                          tagText
                          nodeId
                          commonVarietyId
                        }
                      }
                    }
                    commonSizeId
                    commonSize {
                      id
                      sizeName
                      productSizeId
                      productSize {
                        id
                        combineDescription
                        jvDescription
                      }
                      commonSizeTags {
                        nodes {
                          commonSizeId
                          nodeId
                          tagText
                        }
                      }
                    }
                    commonPackTypeId
                    commonPackType {
                      id
                      packTypeName
                      packMasterId
                      packMaster {
                        id
                        packDescription
                      }
                      commonPackTypeTags {
                        nodes {
                          commonPackTypeId
                          nodeId
                          tagText
                        }
                      }
                    }
                    customerId
                  }
                }
              }
            }
          }
        }
      }
      isPre
      vesselCode
      vesselName
      warehouse {
        id
        warehouseName
      }
    }
  }
}
