query CUSTOMER_DETAILS($id: String!, $orderBy: [PersonContactsOrderBy!]) {
  customer(id: $id) {
    address1
    address2
    city
    countryId
    country {
      countryName
    }
    customerName
    id
    notes
    personContactsByCustomerPersonContactCustomerIdAndPersonContactId(
      orderBy: $orderBy
    ) {
      nodes {
        customersByCustomerPersonContactPersonContactIdAndCustomerId {
          nodes {
            customerName
            id
          }
        }
        email
        firstName
        id
        isPrimary
        lastName
        workPhone
      }
    }
    phone
    postalState
    website
    zipCode
    vendor {
      id
    }
    truckRatesByTruckRateCustomerCustomerIdAndTruckRateId {
      nodes {
        id
        fullLoadRate
        isDefault
        locationDescription
        notes
        palletRate1
        palletRate10
        palletRate11
        palletRate12
        palletRate13
        palletRate14
        palletRate15
        palletRate2
        palletRate3
        palletRate4
        palletRate5
        palletRate6
        palletRate7
        palletRate8
        palletRate9
        postalState
        vendor {
          id
          vendorName
        }
      }
    }
  }
}
