query CUSTOMER_DISTINCT_VALUES(
  $columnName: String
  $conditionName: String
  $conditionValue: String
) {
  customerDistinctValues(
    columnName: $columnName
    conditionName: $conditionName
    conditionValue: $conditionValue
  ) {
    nodes
  }
}
