query CUSTOMER_LIST(
  $city: [String!]
  $postalState: [String!]
  $orderBy: [CustomersOrderBy!]
  $search: String
) {
  customers(
    condition: { active: true }
    filter: {
      city: { in: $city }
      searchText: { includesInsensitive: $search }
      postalState: { in: $postalState }
    }
    orderBy: $orderBy
  ) {
    nodes {
      id
      city
      customerName
      personContactsByCustomerPersonContactCustomerIdAndPersonContactId {
        nodes {
          customersByCustomerPersonContactPersonContactIdAndCustomerId {
            nodes {
              customerName
            }
          }
          email
          firstName
          id
          isPrimary
          lastName
          workPhone
        }
      }
      phone
      postalState
      zipCode
    }
    totalCount
  }
}
